### ISSUE TITLE
Build errors due to missing header file, explicit template instantiation and wrong shared pointer access 

### ISSUE THREAD

**Issue by matzeschmid** [bsubercaseaux/MajorityQueries#1]
There are several issues within your sources. Add the following changes to get it built.
1. Add `#include <memory>` to `bitmap.h` for use of `std::shared_ptr`.
2. Add `template class Bitmap<bool>;` to `bitmap.cpp` for explicit template instantiation for data type `bool`. My recommendation is to add template class definition to header file and remove `bitmap.cpp` and the library `libbitmap.a` from project. Otherwise you have to add explicit template instantiation to `bitmap.cpp` for each new data type used by tests.
3. Fix shared pointer dereference errors in `Bitmap(std::shared_ptr<const std::vector<T>> initVec);`

```
template<class T>
Bitmap<T>::Bitmap(std::shared_ptr<const std::vector<T>> initVec) 
    : vectorRef_(initVec), n_(initVec->size()) {
    rank0_.resize(n_+1);

    for(size_t i = 0; i < n_; ++i) {
        rank0_[i+1] = rank0_[i] + (bool)((*vectorRef_)[i]);
    }

    for(size_t i = 0; i < n_; ++i) {
        select_[(bool)((*vectorRef_)[i])].push_back(i); 
    }
}
```
4. Optional: You can remove `#include <vector>` from `bitmap.cpp` and `test_bitmap.cpp` because it's already part of `bitmap.h`.

**Comment by bsubercaseaux** [comment]
Thanks for your comment!

I only have questions about point 2. Why would I need to explicitly declare in the `bitmap.cpp` that the class is going to be instantiated with a particular data type (such as `bool`)? As you said I'd have to also declare that it will be going to use with `int`, `float`, `double`, etc...

I did both a header and a cpp file so when the class starts growing one can refer to the .h file for a more succinct description of what it does. Isn't that the good practice in these cases?

**Comment by matzeschmid** [comment]
The compiler needs both template class declaration and definition to create template classes of specific types (`bool` in your case). If you first build the template class library without explicit template instantiation the compiler will create nothing. Thus you will get unresolved references reported by the linker. I think the catch library too is just a header file because it contains a lot of template classes.
  
From my point of view there are the following possible solutions:
1. Add both template declaration and definition to the header file. Thus you need no library, just add the header file to your test source file.
2. Add explicit template instantiation for each type to template source file (`bitmap.cpp` in your case). Thus you can either build a library or just add the template class source and header file to your test project. 
3. Include template source file to your test source file. However i think that's not a nice solution.

Hope this helps.
Mathias
